name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: '6.3.0'

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v4.1.0

      - name: Show Version Info
        run: |
          echo "SemVer: ${{ steps.version_step.outputs.semVer }}"
          echo "FullSemVer: ${{ steps.version_step.outputs.fullSemVer }}"
          echo "InformationalVersion: ${{ steps.version_step.outputs.informationalVersion }}"
      
      - name: Create and push Git tag 
        run: |
          TAG="v${{ steps.version_step.outputs.MajorMinorPatch }}"
          echo "Planned tag: $TAG"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # tag adnotowany (lepszy do historii)
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

          echo "Pushed tag $TAG"
